spring:
  r2dbc:
    url: r2dbc:h2:mem:///test?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=FALSE;mode=mysql
    name: spring
    username: spring
    password: spring
  sql:
    init:
      mode: embedded
      encoding: UTF-8
      schema-locations: db/schema.sql
      data-locations: db/data.sql
