INSERT INTO book VALUES (1, "Spring in Action")
INSERT INTO book VALUES (2, "Spring in Practice")
INSERT INTO book VALUES (3, "Spring Boot in Action")
INSERT INTO book VALUES (4, "Spring Boot in Practice")
INSERT INTO book VALUES (5, "Spring Security in Action")
INSERT INTO book VALUES (6, "Spring Security in Practice")
INSERT INTO book VALUES (7, "Spring Data in Action")
INSERT INTO book VALUES (8, "Spring Data in Practice")
INSERT INTO book VALUES (9, "Spring Cloud in Action")
INSERT INTO book VALUES (10, "Spring Cloud in Practice")
INSERT INTO book VALUES (11, "Spring Cloud Data in Action")
INSERT INTO book VALUES (12, "Spring Cloud Data in Practice")
INSERT INTO book VALUES (13, "Spring Cloud Security in Action")
INSERT INTO book VALUES (14, "Spring Cloud Security in Practice")
INSERT INTO book VALUES (15, "Spring Cloud Streams in Action")
INSERT INTO book VALUES (16, "Spring Cloud Streams in Practice")
