INSERT INTO books VALUES (1, "Spring in Action")
INSERT INTO books VALUES (2, "Spring in Practice")
INSERT INTO books VALUES (3, "Spring Boot in Action")
INSERT INTO books VALUES (4, "Spring Boot in Practice")
INSERT INTO books VALUES (5, "Spring Security in Action")
INSERT INTO books VALUES (6, "Spring Security in Practice")
INSERT INTO books VALUES (7, "Spring Data in Action")
INSERT INTO books VALUES (8, "Spring Data in Practice")
INSERT INTO books VALUES (9, "Spring Cloud in Action")
INSERT INTO books VALUES (10, "Spring Cloud in Practice")
INSERT INTO books VALUES (11, "Spring Cloud Data in Action")
INSERT INTO books VALUES (12, "Spring Cloud Data in Practice")
INSERT INTO books VALUES (13, "Spring Cloud Security in Action")
INSERT INTO books VALUES (14, "Spring Cloud Security in Practice")
INSERT INTO books VALUES (15, "Spring Cloud Streams in Action")
INSERT INTO books VALUES (16, "Spring Cloud Streams in Practice")
